# Generated by Django 3.1.4 on 2021-01-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20210105_0549"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ebooks",
            name="publication_date",
            field=models.DateField(),
        ),
    ]
