# Generated by Django 3.1.4 on 2021-01-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20210105_0613"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="say",
            field=models.TextField(blank=True),
        ),
    ]
